default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  url: postgresql://localhost:15432/sidespin_development

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] || 'postgresql://localhost/sidespin_test' %>

production:
  url: <%= ENV['DATABASE_URL'] %>
